Homework2 Leon Kochiev
made-mlops-2022/leon_kochiev pull request #2
Opened 2022-11-24 05:08 UTC by nullkatar

2022-11-26 06:44 UTC, bulaevvi commented
У меня в моем окружении Win10 не получилось запустить Ваш контейнер, передаю на проверку другим коллегам

2022-12-14 06:26 UTC, SVizor42 commented on app/api.py
> +from app.schemas import Input
Локальные импорты следуют после стандартных библиотек

2022-12-14 13:40 UTC, SVizor42 requested changes
Работа сырая, некоторые моменты под вопросом:
1. Нужно убрать лишние папки - `pycache` и т.д.
2. Не совсем понятен момент с запуском кучи shell скриптов. Для продакшн решения выглядит так себе. Почему сразу просто не сделать ENTRYPOINT с запускам сервиса через `gunicorn` / `uvicorn`?
3. В описании команд также есть неточности в именах файлов и путей. Так и не удалось протыкать сервис после манипуляций и запуска докер контейнера.

2022-12-14 16:55 UTC, nullkatar commented
@SVizor42 всё зафиксил, должно работать. По поводу баш скриптов - не знаю, мне так гораздо удобнее. И мы это используем на работе, чтобы можно было не запоминать название контейнеров, юзеров из них. да и кажется что такие интуитивные названия для скриптов тоже очень к месту, сразу понятно что надо делать.

2022-12-15 08:23 UTC, SVizor42 commented on example.sh
> +python3 sender.py http://localhost:8080/predict -d '{"data": [{"age":24, "sex":1, "cp":1, "trestbps":100, "chol":228, "fbs":0, "restecg":0, "thalach":100, "exang":0, "oldpeak":228.322, "slope":0, "ca
Тут все-таки `client.py`?

2022-12-15 08:24 UTC, SVizor42 commented on app/api.py
> +)
Я же правильно понял, что тут и креды в самой ссылке?

2022-12-15 08:26 UTC, nullkatar commented on app/api.py
> +)
da

2022-12-15 08:26 UTC, SVizor42 approved these changes
Ок, в таком виде валидно.

**Сумма: 21 балл**

Можно сливать ветку.

2022-12-15 08:26 UTC, SVizor42 commented on app/api.py
> +)
Только в проде так не делайте :)

2022-12-15 08:28 UTC, nullkatar commented on example.sh
> +python3 sender.py http://localhost:8080/predict -d '{"data": [{"age":24, "sex":1, "cp":1, "trestbps":100, "chol":228, "fbs":0, "restecg":0, "thalach":100, "exang":0, "oldpeak":228.322, "slope":0, "ca
да, верно.

2022-12-15 08:30 UTC, merged

2022-12-15 08:32 UTC, nullkatar commented
@SVizor42 я всё закрыл и согласен с оценкой. На всякий случай решил написать тут как сообщение, а то вдруг вы не увидите и не поставите оценочку.