Homework3
made-mlops-2022/leon_kochiev pull request #3
Opened 2022-11-30 19:33 UTC by nullkatar

еле успел

2022-12-07 09:24 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста". У Вас нет скриншотов дагов в исполненном виде. См. пример скриншотов в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:28 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-15 03:50 UTC, nullkatar commented
![3](https://user-images.githubusercontent.com/27498544/207768223-4a266c5c-1f9b-4d26-8407-ed65fbfe258a.jpg)
![4](https://user-images.githubusercontent.com/27498544/207768226-91951074-5d91-4207-8d66-af8ae772c1a3.jpg)
![1](https://user-images.githubusercontent.com/27498544/207768228-b448e29b-61ac-4125-ba9c-dd6681a451b8.jpg)
![2](https://user-images.githubusercontent.com/27498544/207768229-2f3d030e-68f1-4be8-a658-39ac6f707a20.jpg)

@bulaevvi

2022-12-20 11:22 UTC, bulaevvi commented on dags/predict.py
> +}
Этот блок повторяется в трех модулях. Можно было вынести в отдельный модуль

2022-12-20 11:24 UTC, bulaevvi approved these changes
Итого 42 балла. Делайте merge

2022-12-21 18:44 UTC, merged